defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: pontodevista_development

test:
  <<: *defaults
  database: pontodevista_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
