require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe NewsFeedsController do

  def mock_news_feed(stubs={})
    @mock_news_feed ||= mock_model(NewsFeed, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all news_feeds as @news_feeds" do
      NewsFeed.stub(:all) { [mock_news_feed] }
      get :index
      assigns(:news_feeds).should eq([mock_news_feed])
    end
  end

  describe "GET show" do
    it "assigns the requested news_feed as @news_feed" do
      NewsFeed.stub(:find).with("37") { mock_news_feed }
      get :show, :id => "37"
      assigns(:news_feed).should be(mock_news_feed)
    end
  end

  describe "GET new" do
    it "assigns a new news_feed as @news_feed" do
      NewsFeed.stub(:new) { mock_news_feed }
      get :new
      assigns(:news_feed).should be(mock_news_feed)
    end
  end

  describe "GET edit" do
    it "assigns the requested news_feed as @news_feed" do
      NewsFeed.stub(:find).with("37") { mock_news_feed }
      get :edit, :id => "37"
      assigns(:news_feed).should be(mock_news_feed)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created news_feed as @news_feed" do
        NewsFeed.stub(:new).with({'these' => 'params'}) { mock_news_feed(:save => true) }
        post :create, :news_feed => {'these' => 'params'}
        assigns(:news_feed).should be(mock_news_feed)
      end

      it "redirects to the created news_feed" do
        NewsFeed.stub(:new) { mock_news_feed(:save => true) }
        post :create, :news_feed => {}
        response.should redirect_to(news_feed_url(mock_news_feed))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved news_feed as @news_feed" do
        NewsFeed.stub(:new).with({'these' => 'params'}) { mock_news_feed(:save => false) }
        post :create, :news_feed => {'these' => 'params'}
        assigns(:news_feed).should be(mock_news_feed)
      end

      it "re-renders the 'new' template" do
        NewsFeed.stub(:new) { mock_news_feed(:save => false) }
        post :create, :news_feed => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested news_feed" do
        NewsFeed.stub(:find).with("37") { mock_news_feed }
        mock_news_feed.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :news_feed => {'these' => 'params'}
      end

      it "assigns the requested news_feed as @news_feed" do
        NewsFeed.stub(:find) { mock_news_feed(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:news_feed).should be(mock_news_feed)
      end

      it "redirects to the news_feed" do
        NewsFeed.stub(:find) { mock_news_feed(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(news_feed_url(mock_news_feed))
      end
    end

    describe "with invalid params" do
      it "assigns the news_feed as @news_feed" do
        NewsFeed.stub(:find) { mock_news_feed(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:news_feed).should be(mock_news_feed)
      end

      it "re-renders the 'edit' template" do
        NewsFeed.stub(:find) { mock_news_feed(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested news_feed" do
      NewsFeed.stub(:find).with("37") { mock_news_feed }
      mock_news_feed.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the news_feeds list" do
      NewsFeed.stub(:find) { mock_news_feed }
      delete :destroy, :id => "1"
      response.should redirect_to(news_feeds_url)
    end
  end

end
